version: "3.4"
services:
    database:
        build: ./db_container         
    webservice:
        build: ./web_container
        ports:
            - 5000:5000
        depends_on:
            - database
            